var config = {
    title: "Yuma, AZ",
    imageName: "image-resize.jpg",
    location: "Yuma",
    latitude: 32.698,
    longitude: -114.650,
    az: 180,
    camera: "RPiHQ",
    computer: "Raspberry Pi 3 B+",
    owner: "Jason Hitesman",
    auroraMap: "north",
    overlaySize: 875,
    overlayOffsetLeft: -20,
    overlayOffsetTop: 5,
}
